version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: testsage-db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./create-db.sql:/docker-entrypoint-initdb.d/01-create-db.sql
      - ./init.sql:/docker-entrypoint-initdb.d/02-init.sql
    networks:
      - testsage-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: testsage-api
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - testsage-net

volumes:
  postgres_data:

networks:
  testsage-net:
